### PR TITLE
Feature/apps 442 selfid did session support

### PR DESCRIPTION
**Pull request by zachferland**
Creates webclient that supports did-session, adds flags to enable session when using web or react packages.

### CODE REVIEW

**Comment by PaulLeCam** [comment]
@zachferland can you change the base branch to `develop` so we can deploy to dev first please?

**Comment by zachferland** [comment]
@PaulLeCam didnt see any dev/develop branch before, is it clay? clay looks like its not up to date

**Comment by PaulLeCam** [comment]
@zachferland yeah looks like it's missing, might have been deleted with a previous merge. Can you use the clay branch then please?

**Comment by zachferland** [comment]
git history ended up really messy, not sure what happen to clay vs main at some point, but the diff here is correct now

**Review by PaulLeCam — APPROVED** [review]

**Pull request merged**
